# Generated by Django 4.0.6 on 2022-08-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Develop', '0002_contact_date_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='query',
            field=models.TextField(),
        ),
    ]
